version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: PIAB2026DayStudies-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - PIAB2026DayStudies-data:/var/opt/mssql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  PIAB2026DayStudies-data: