// <auto-generated />
using System;
using Company.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.Data.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20260416144943_CartMigration")]
    partial class CartMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company.Data.Data.CMS.News", b =>
                {
                    b.Property<int>("IdNews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNews"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("LinkTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdNews");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            IdNews = 1,
                            Content = "We are excited to launch our latest product.",
                            DisplayOrder = 1,
                            LinkTitle = "New Product",
                            Title = "Announcing Our New Product"
                        },
                        new
                        {
                            IdNews = 2,
                            Content = "We have partnered with XYZ Corp to expand our reach.",
                            DisplayOrder = 2,
                            LinkTitle = "Partnership",
                            Title = "New Partnership with XYZ Corp"
                        },
                        new
                        {
                            IdNews = 3,
                            Content = "We are proud to be recognized for our achievements.",
                            DisplayOrder = 3,
                            LinkTitle = "Award",
                            Title = "We Won an Industry Award"
                        });
                });

            modelBuilder.Entity("Company.Data.Data.CMS.Page", b =>
                {
                    b.Property<int>("IdPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPage"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("LinkTitle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdPage");

                    b.ToTable("Page");

                    b.HasData(
                        new
                        {
                            IdPage = 1,
                            Content = "We are a leading provider of innovative solutions.",
                            DisplayOrder = 1,
                            LinkTitle = "About Us",
                            Title = "About Our Company"
                        },
                        new
                        {
                            IdPage = 2,
                            Content = "We offer a wide range of services to meet your needs.",
                            DisplayOrder = 2,
                            LinkTitle = "Services",
                            Title = "Our Services"
                        },
                        new
                        {
                            IdPage = 3,
                            Content = "Get in touch with us for more information.",
                            DisplayOrder = 3,
                            LinkTitle = "Contact",
                            Title = "Contact Us"
                        });
                });

            modelBuilder.Entity("Company.Data.Data.Shop.CartItem", b =>
                {
                    b.Property<int>("IdCartItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCartItem"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("IdSessionOfCart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCartItem");

                    b.HasIndex("IdProduct");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCategory");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Description = "Find the latest electronic gadgets.",
                            Name = "Electronics"
                        },
                        new
                        {
                            IdCategory = 2,
                            Description = "Discover a world of knowledge.",
                            Name = "Books"
                        },
                        new
                        {
                            IdCategory = 3,
                            Description = "Shop for the latest fashion trends.",
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("Company.Data.Data.Shop.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<bool>("IsDiscount")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdCategory");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            IdProduct = 1,
                            Code = "ELEC-001",
                            Description = "A powerful and feature-rich smartphone.",
                            FotoURL = "https://via.placeholder.com/150",
                            IdCategory = 1,
                            IsDiscount = false,
                            Name = "Smartphone",
                            Price = 699.99m
                        },
                        new
                        {
                            IdProduct = 2,
                            Code = "BOOK-001",
                            Description = "A classic novel by F. Scott Fitzgerald.",
                            FotoURL = "https://via.placeholder.com/150",
                            IdCategory = 2,
                            IsDiscount = false,
                            Name = "The Great Gatsby",
                            Price = 12.99m
                        },
                        new
                        {
                            IdProduct = 3,
                            Code = "CLTH-001",
                            Description = "A comfortable and stylish t-shirt.",
                            FotoURL = "https://via.placeholder.com/150",
                            IdCategory = 3,
                            IsDiscount = false,
                            Name = "T-Shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            IdProduct = 4,
                            Code = "ELEC-002",
                            Description = "A high-performance laptop for work and play.",
                            FotoURL = "https://via.placeholder.com/150",
                            IdCategory = 1,
                            IsDiscount = false,
                            Name = "Laptop",
                            Price = 1299.99m
                        },
                        new
                        {
                            IdProduct = 5,
                            Code = "BOOK-002",
                            Description = "A timeless story of justice and prejudice.",
                            FotoURL = "https://via.placeholder.com/150",
                            IdCategory = 2,
                            IsDiscount = false,
                            Name = "To Kill a Mockingbird",
                            Price = 14.99m
                        });
                });

            modelBuilder.Entity("Company.Data.Data.Shop.CartItem", b =>
                {
                    b.HasOne("Company.Data.Data.Shop.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.Product", b =>
                {
                    b.HasOne("Company.Data.Data.Shop.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
